[package]
name = "atsamd21-hal"
version = "0.0.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]
description = "HAL and Peripheral access API for ATSAMD21 microcontrollers"
keywords = ["no-std", "arm", "cortex-m", "hal", "embedded-hal", "hardware-support", "embedded"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/wez/atsamd21-rs"

[dependencies]
cortex-m = "~0.4"
embedded-hal = "~0.1"
nb = "~0.1"

[dependencies.atsamd21g18a]
path = "../atsamd21g18a"
version = "~0.2"

[features]
rt = ["atsamd21g18a/rt"]
unproven = ["embedded-hal/unproven"]
