[package]
name = "atsamd21-hal"
version = "0.0.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]

[dependencies]
cortex-m = "~0.4"
embedded-hal = "~0.1"
nb = "~0.1"

[dependencies.atsamd21g18a]
path = "../atsamd21g18a"

[features]
rt = ["atsamd21g18a/rt"]
unproven = ["embedded-hal/unproven"]
