language: rust
cache: cargo

jobs:
  include:
    - stage: build
      script:
        - rustup target add thumbv6m-none-eabi
        - rustup target add thumbv7em-none-eabihf
        - ./build-all.sh
    - rust: 'nightly'
      script:
        - rustup target add thumbv6m-none-eabi
        - rustup target add thumbv7em-none-eabihf
        - ./build-all.sh
    - stage: Document-and-Deploy
      rust: 'nightly'
      script:
        - rustup target add thumbv6m-none-eabi
        - rustup target add thumbv7em-none-eabihf
        - ./build-docs.py
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        local-dir: doc

stages:
  - build 
  - name: Document-and-Deploy
    if: (NOT type IN (pull_request)) AND (branch = master)
