language: rust
cache: cargo

jobs:
  include:
    - stage: build
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> f78999857... travis test 2
=======
      rust:
        - stable
        - nightly
>>>>>>> c5ec8528f... travis test 18
=======
>>>>>>> 94fe3ff74... travis test 20
=======
    - rust:
        - stable
        - nightly
>>>>>>> e67433712... travis test 21
      script:
        - rustup target add thumbv6m-none-eabi
        - rustup target add thumbv7em-none-eabihf
        - ./build-all.sh
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    - rust: 'stable'
>>>>>>> cbc790205... travis test 22
    - rust: 'nightly'
=======
      rust: 'stable'
      rust: 'nightly'
>>>>>>> 30d117a32... travis test 23
=======
      - rust: 'stable'
        script:
          - rustup target add thumbv6m-none-eabi
        - rustup target add thumbv7em-none-eabihf
        - ./build-all.sh
      - rust: 'nightly'
>>>>>>> 28cd9b467... travis test 24
=======
    - rust: 'stable'
=======
>>>>>>> fbfdd27e2... travis test 26
      script:
        - rustup target add thumbv6m-none-eabi
        - rustup target add thumbv7em-none-eabihf
        - ./build-all.sh
    - rust: 'nightly'
>>>>>>> 6d023decf... travis test 25
      script:
        - rustup target add thumbv6m-none-eabi
        - rustup target add thumbv7em-none-eabihf
        - ./build-all.sh
<<<<<<< HEAD
<<<<<<< HEAD
    - stage: Document-and-Deploy
      rust: 'nightly'
      script:
        - rustup target add thumbv6m-none-eabi
        - rustup target add thumbv7em-none-eabihf
        - ./build-docs.py
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        local-dir: doc
=======
    script:
      - rustup target add thumbv6m-none-eabi
      - rustup target add thumbv7em-none-eabihf
      - ./build-all.sh
    - stage: doc
      [ $TRAVIS_BRANCH = master ] &&
      [ $TRAVIS_PULL_REQUEST = false ] &&
      ./build-docs.py
>>>>>>> c6baea45d... travis test
=======
    - stage: doc
=======
>>>>>>> 42f5e795a... travis test 8
      on: 
        rust: 
          - nightly
          - stable
=======
      rust:
        - nightly
        - stable
>>>>>>> 153b43cc6... travis test 10
=======
      on:
        rust:
          - nightly
          - stable
>>>>>>> 269db9355... travis test 11
    - stage: docs
=======
      rust:
        - nightly
        - stable
=======
      rust: 'stable'
      rust: 'nightly'
>>>>>>> a1514df76... travis test 13
    - stage: document
>>>>>>> d1413be14... travis test 12
=======
      rust: 
        - stable
        - nightly
=======
>>>>>>> 395e22804... travis test 16
    - stage: "Document & Deploy"
<<<<<<< HEAD
>>>>>>> 4545dadea... travis test 14
=======
        rust: 'nightly'
>>>>>>> c5ec8528f... travis test 18
=======
    - stage: 
        name: "Document & Deploy"
        rust:
          - nightly
>>>>>>> ed2c49f10... travis test 19
=======
    - stage: Document_and_Deploy
=======
    - stage: Document and Deploy
>>>>>>> 28cd9b467... travis test 24
=======
    - stage: Document-and-Deploy
>>>>>>> 6d023decf... travis test 25
      rust: 'nightly'
>>>>>>> 94fe3ff74... travis test 20
      script:
        - rustup target add thumbv6m-none-eabi
        - rustup target add thumbv7em-none-eabihf
        - ./build-docs.py
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> f78999857... travis test 2

stages:
  - build 
  - name: Document-and-Deploy
    if: (NOT type IN (pull_request)) AND (branch = master)
=======
    - stage: deploy
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      keep-history: false
      local-dir: doc
      on:
        branch: master
        rust: 'nightly'
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> e17217ec6... travis test 3
=======
  exclude:
<<<<<<< HEAD
    - test
>>>>>>> 097736b68... travis test 4
=======
    - stage: test
>>>>>>> 8474fd194... travis test 5
=======
  allow_failures:
<<<<<<< HEAD
    test
>>>>>>> dc14bf8e8... travis test 6
=======
    - stage: test
>>>>>>> dda40ff8f... travis test 7
=======
      on:
        branch: master
        rust:
          - nightly
  exclude:
<<<<<<< HEAD
    - stage: Test
>>>>>>> 42f5e795a... travis test 8
=======
    - stage: "Test"
>>>>>>> 137f7b308... travis test 9
=======
      rust:
        - nightly
=======
      rust: 'nightly'
>>>>>>> a1514df76... travis test 13
    - stage: deploy
      script: skip
=======
>>>>>>> 4545dadea... travis test 14
=======
      on:
        rust: 'nightly'
>>>>>>> 395e22804... travis test 16
=======
>>>>>>> c5ec8528f... travis test 18
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        local-dir: doc

stages:
  - build 
  - name: document
    if: branch = master
  - name: deploy
    if: branch = master
>>>>>>> d1413be14... travis test 12
