[workspace]

[package]
name = "samd21"
version = "0.0.0"

[dependencies]
cortex-m = "~0.4"
cortex-m-rt = "~0.4"
cortex-m-semihosting = "~0.2"
panic-semihosting = "~0.1"
panic-abort = "~0.1"
sx1509 = { git = "https://github.com/wez/sx1509.git" }

[features]
use_semihosting = []

[dependencies.atsamd21-hal]
path = "hal"
features = ["rt", "unproven"]

[profile.release]
debug = true
lto = true
