[workspace]

[package]
name = "samd21"
version = "0.0.0"

[dependencies]
cortex-m = "0.4.3"
cortex-m-semihosting = "0.2.0"

[dependencies.cortex-m-rt]
version = "0.3.13"
features = ["abort-on-panic"]

[dependencies.atsamd21-hal]
path = "hal"
features = ["rt", "unproven"]

# disable both incremental compilation and parallel codegen to
# reduce the chances of running into rust-lang/rust#47074
[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
debug = true
lto = true
